# Generated by Django 2.2.5 on 2019-11-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_login_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_choices',
            new_name='login_method',
        ),
    ]
